version: '3.7'

services:

  core:
    build:
      context: ./core
    container_name: core
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - 1865
    ports:
      - 1865:80
    volumes:
      - ./core:/app
    command:
      - uvicorn
      - cat.main:cheshire_cat_api
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --log-config
      - ./logger.yml
      - --reload # take away in prod
    restart: unless-stopped

  frontend:
    build:
      context: ./admin
    container_name: admin
    depends_on:
      - core
    ports:
      - 3000:3000
    volumes:
      - ./admin:/app
    restart: unless-stopped
