version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web
    expose:
      #- 1865
      - 80
    ports:
      - 80:80
    volumes:
      - ./web:/app
    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --reload # take away in prod
    restart: unless-stopped

  vector-memory:
    image: qdrant/qdrant:v1.0.0
    container_name: vector-memory
    depends_on:
      - web
    ports:
      - 6333:6333
    volumes:
      - ./long_term_memory/qdrant:/qdrant/storage
