version: '3.7'

services:

  web:
    build:
      context: ./web
    container_name: web
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - 1865
    ports:
      - 1865:80
    volumes:
      - ./web:/app
    command:
      - uvicorn
      - cat.main:cheshire_cat_api
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --log-config
      - ./logger.yml
      - --reload # take away in prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - web
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    restart: unless-stopped
