version: '3.7'

services:

  web:
    build:
      context: ./web
    container_name: web
    depends_on:
      - vector-memory
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - 1865
    ports:
      - 1865:80
    volumes:
      - ./web:/app
    command:
      - uvicorn
      - cat.main:cheshire_cat_api
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --reload # take away in prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - web
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm run build && npm run dev"
    restart: unless-stopped

  vector-memory:
    image: qdrant/qdrant:v1.0.1
    container_name: vector-memory
    ports:
      - 6333:6333
    volumes:
      - ./long_term_memory/qdrant:/qdrant/storage
    restart: unless-stopped
  #vector-memory:
  #  image: semitechnologies/weaviate:1.17.3
  #  container_name: vector-memory
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - ./long_term_memory/weaviate:/var/lib/weaviate
  #  restart: unless-stopped
