version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web
    expose:
      #- 1865
      - 80
    ports:
      - 80:80
    volumes:
      - ./web:/app
    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --reload # take away in prod
    restart: unless-stopped
