name: Cheshire-Cat Action on Pull Requests
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "master"

jobs:
  pylint:
    name: "Coding Standards"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Download
        uses: actions/checkout@v3
      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Download python dependencies
        run: pip install .[dev]
      - name: Pylint
        run: pylint -f actions ./
