name: Cheshire Cat Action create tag

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
      - "feature/tag_workflow"
    tags:
      - "*.*.*"

permissions:
  contents: write

env:
  PLUGIN_JSON: "0.0.1"
  TAG_EXISTS: false

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: '/core/pyproject.toml'
          field: 'project.version'
      - name: Publish tag
        if: env.TAG_EXISTS == false
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{steps.read_toml.outputs.value}}"
          tag_exists_error: false
